(ns mgl-mail.desktop.screens.home
  (:require
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]
   [mgl-mail.desktop.screens.signup :as signup]
   [mgl-mail.states.global :refer [state]]))
   
(defn screen 
  []
  (f/widget
   :watch [{account :account} state]
   (cond
     (empty? account)
     (signup/screen)

     :else
     (f/widget
      (m/Scaffold)
      .body
      (m/Center)
      (m/Text "Home")))))
