(ns mail-app.mobile
  (:require ["package:flutter/material.dart" :as m]
            ["package:flutter_styled_toast/flutter_styled_toast.dart" :as st]
            [cljd.flutter :as f]
            [mail-app.desktop.toast :as toast]
            [mail-app.mobile.screens.home :as home]
            [mail-app.mobile.screens.compose :as compose]
            [mail-app.mobile.screens.mail-detail :as mail-detail]
            [mail-app.mobile.screens.search :as search]
            [mail-app.mobile.screens.settings :as settings]
            [mail-app.mobile.screens.signup :as signup]
            [mail-app.theme :as theme]))

(defn app []
  (f/widget
   :managed [nav-key (#/(m/GlobalKey m/NavigatorState))]
   (m/MaterialApp
    .navigatorKey nav-key
    .title "MGL Mail"
    .debugShowCheckedModeBanner false
    .theme (theme/sky-theme)
    .builder
    (fn [_ctx child]
      (st/StyledToast
       .child
       (f/widget
        :context host-ctx
        (do
          (toast/remember-root-ctx! host-ctx)
          (or child (m/SizedBox.shrink))))))
    .initialRoute "/"
    .routes {"/" (fn ^m/Widget [_] (home/screen))
             "/compose" (fn ^m/Widget [_] (compose/screen))
             "/mail_detail" (fn ^m/Widget [_] (mail-detail/screen))
             "/search" (fn ^m/Widget [_] (search/screen))
             "/settings" (fn ^m/Widget [_] (settings/screen))
             "/signup" (fn ^m/Widget [_] (signup/screen))})))
